version: '2'
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - /pathToProject/flaskstarterapp:/opt/flaskstarterapp
    links:
      #- db:mongodb
       - db:postgresdb
    container_name: flaskstarterapp_web_1
  db:
    #image: mongo:3.0.2
    image: postgres:latest
    container_name: flaskstarterapp_db_1


    #docker-compose build
    #docker-compose up -d db
    #docker-compose run --service-ports web